spring.application.name=ZorvynFinance

spring.mongodb.database=zorvyndb
spring.mongodb.uri=mongodb://localhost:27017

#should be kept in env variables of machine - for dev it is here
jwt.secret.key=fasfdlkajsdflfaksejfhakjfhaksjffasdfsadfasdf

app.rate-limit.max-requests=120
app.rate-limit.window-seconds=60
