spring.application.name=ZorvynFinance

spring.mongodb.database=zorvyndb
spring.mongodb.uri=mongodb://localhost:27017

jwt.secret.key=fasfdlkajsdflfaksejfhakjfhaksjffasdfsadfasdf

app.rate-limit.max-requests=120
app.rate-limit.window-seconds=60
